name: mgeasysim
channels:
  - conda-forge
  - bioconda
dependencies:
  - pytest
  - jupyterlab
  - seaborn
  - matplotlib
  - numpy
  - pandas
  - rapidfuzz
  - ca-certificates
  - certifi
  - openssl
  - ncbi-datasets-cli
  - mash
  - tqdm
  - biopython
  - python=3.12
  - sylph
  - art